apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops
  labels: { app: devsecops }
spec:
  replicas: 1                       # можно вернуть 2 позже
  selector:
    matchLabels: { app: devsecops }
  template:
    metadata:
      labels: { app: devsecops }
    spec:
      containers:
        - name: devsecops-container
          image: IMAGE_PLACEHOLDER  # <-- совпадает с sed
          imagePullPolicy: Always
          ports:
            - containerPort: 8080   # Spring Boot по умолчанию
---
apiVersion: v1
kind: Service
metadata:
  name: devsecops-svc
  labels: { app: devsecops }
spec:
  type: NodePort
  selector: { app: devsecops }
  ports:
    - port: 8080
      targetPort: 8080
